baseURL = 'http://andresatencio.github.io'
languageCode = 'en-us'
title = 'Blog'
theme = 'archie'
copyright = "Andres Atencio"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/andresatencio"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/atencioandres"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/andres.atencio2"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3